In [6]:
import numpy as np
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [2]:
import numpy as np
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [10]:
np.arange(1,30,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [11]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [12]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
np.arange(2,15)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.linspace(0,1,15)

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

In [18]:
np.random.rand(3,5)

array([[0.7836588 , 0.33224147, 0.73291329, 0.83833063, 0.95509368],
       [0.34165748, 0.49045921, 0.07675846, 0.23434575, 0.70176589],
       [0.05748   , 0.94506448, 0.47676058, 0.27942321, 0.05927138]])

In [19]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
np.random.randn(2,4)

array([[ 0.06390228, -0.84489361,  0.66363342, -0.74178172],
       [-1.56301806, -1.73986845, -1.36678405,  0.28631123]])

In [21]:
np.random.randint(20,56,100)

array([55, 25, 24, 52, 38, 37, 49, 43, 54, 48, 24, 29, 35, 27, 55, 37, 47,
       42, 55, 22, 50, 53, 30, 31, 27, 34, 32, 34, 52, 20, 49, 24, 44, 24,
       34, 43, 27, 51, 20, 49, 41, 21, 55, 50, 37, 53, 26, 29, 41, 50, 39,
       27, 26, 26, 55, 52, 28, 24, 32, 30, 44, 32, 27, 38, 54, 47, 42, 39,
       33, 49, 37, 30, 39, 46, 33, 36, 54, 31, 34, 52, 36, 54, 26, 51, 23,
       21, 47, 22, 28, 50, 54, 29, 31, 38, 51, 32, 21, 47, 51, 21])

In [27]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [28]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [2]:
import numpy as np
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [4]:
sample_matrix[1,2]

21

In [5]:
sample_matrix[2:]

array([[56, 76, 24,  7]])

In [6]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [7]:
sample_matrix[2]

array([56, 76, 24,  7])

In [ ]:
###pandas

In [3]:
import pandas as pd
import numpy as np
lables=['w','x','y','z']
sample_list=[100,200,300,400]
array  =np.array([1,2,3,4])
dict={'w':10,'x':20,'y':30,'z':40}
